name: Deploy Documentation

on:
  push:
    branches:
      - main  # Runs when pushing to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: java-tutorial
          python-version: "3.13.2"
          auto-activate-base: false

      - name: Install Dependencies
        shell: bash -l {0}
        run: |
          conda activate java-tutorial
          pip install sphinx sphinx-rtd-theme myst-parser

      - name: Build Documentation
        shell: bash -l {0}
        run: |
          conda activate java-tutorial
          sphinx-build -b html docs/source docs/build/html

      - name: Commit Built Documentation
        shell: bash -l {0}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/build/html
          git commit -m "Update built documentation [skip ci]" || echo "No changes to commit"
          git push origin main
